---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
  labels:
    name: prometheus-conf
data:
  prometheus.rules: |-
    groups:
    - name: mocked-app alerts
      rules:
      - alert: Instance not in sync
        expr: in_sync != 1
        for: 30s
        labels:
          severity: high
        annotations:
          summary: Instance not in sync
      - alert: Cert expired
        expr: time() - cert_expiration > 0
        for: 30s
        labels:
          severity: medium
        annotations:
          summary: The node cert has expired
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager.<test_namespace>.svc:9093"

    scrape_configs:
      - job_name: 'mocked-app'
        static_configs:
          - targets:
            - 'mocked-app-0.mocked-app.<test_namespace>.svc.cluster.local:8080'
            - 'mocked-app-1.mocked-app.<test_namespace>.svc.cluster.local:8080'
            - 'mocked-app-2.mocked-app.<test_namespace>.svc.cluster.local:8080'
